[Root]
elems = [
    {anchor=40, guide=[0, 0, 10, 10], string="f ../images/491.png", func='forward', para='aa'},
    {anchor=40, guide=[0, 0], string="t ../images/491.png", func='forward', para='aa'},
    {anchor=56, guide=[0, 0], string="path", func='forward', para='aa'},
]
[Edge]
elems = []