blockSet=[
    "../resources/images/blocks/00.png",
    "../resources/images/blocks/01.png",
    "../resources/images/blocks/10.png",
    # "../resources/images/blocks/11.png",
    "../resources/images/blocks/20.png"
]