pageSet = [
    {name='Root', elemSet=[
        {anchor=31, guide=[0, 0, 2, 2], type="FILE", info="../resources/images/491.gif"},
        {anchor=49, guide=[0, 0, 1, 1], type="TEXT", info="The dead can be cured."},
        {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="Title", func='forward', para='Title'},
    ]},
    {name='Edge', elemSet=[
        {anchor=31, type="TEXT", info="""The edge of menu system, it shouldn't appear.
        If you are watching it, there is a bug need to be fixed."""},
        {anchor=49, type="TEXT", info="[R2R]", func='clear'}
    ]},
    {name='Title', elemSet=[
        {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="<<< Root.", func='clear'},
        {anchor=31, guide=[0, 0, 1, 1], type="TEXT", info="THE MAZE"},
        {anchor=49, guide=[0, 0, 1, 1], type="TEXT", info="Setting", func='forward', para='Setting'},
    ]},
    {name='Setting', elemSet = [
        {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="<<<", func='backward'},
        {anchor=49, guide=[0, 10, 1, 1], type="TEXT", info="Go Test?.", func='forward', para='Setting'},
    ]},
]