geneSet = [
    {name="You",           color=[35, 92, 68]   },
    {name="Phage",         color=[49, 117, 69]  },
    {name="Uncertain Cat", color=[66, 143, 66]  },
    {name="Phantom",       color=[110, 168, 74] },
    {name="Crossing",      color=[179, 68, 40]  },
    {name="Five",          color=[209, 102, 48] },
    {name="Plague",        color=[230, 141, 62] },
    {name="Mermaid",       color=[237, 172, 74] },
    {name="Mimesis",       color=[148, 57, 137] },
    {name="Synchron",      color=[179, 80, 141] },
    {name="Frames",        color=[204, 107, 138]},
    {name="Long Loong",    color=[230, 148, 143]},
]