blockSet=[
    "/Users/shilianshen/Documents/Oolong Press/Lo-Tri/src/maze/block/blocks/00.png",
    "/Users/shilianshen/Documents/Oolong Press/Lo-Tri/src/maze/block/blocks/01.png",
    "/Users/shilianshen/Documents/Oolong Press/Lo-Tri/src/maze/block/blocks/10.png",
    "/Users/shilianshen/Documents/Oolong Press/Lo-Tri/src/maze/block/blocks/11.png"
]