# support *.png
[Root]
elems = [
    {anchor=31, guide=[0, 0, 2, 2], type="FILE", info="../images/491.gif"},
    {anchor=49, guide=[0, 0, 1, 1], type="TEXT", info="The dead can be cured."},
    {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="Title", func='forward', para='Title'},
    # {anchor=31, guide=[0, 0, 1, 1], string="t THE MAZE"},
]
[Title]
elems = [
    {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="<<< Root.", func='clear'},
    {anchor=31, guide=[0, 0, 1, 1], type="TEXT", info="THE MAZE"},
    {anchor=49, guide=[0, 0, 1, 1], type="TEXT", info="Setting", func='forward', para='Setting'},
]
[Setting]
elems = [
    {anchor=20, guide=[0, 0, 1, 1], type="TEXT", info="<<<", func='backward'},
    {anchor=49, guide=[0, 50, 1, 1], type="TEXT", info="Go Test?.", func='forward', para='Setting'},
]
[Edge]
elems = [
    {anchor=31, type="TEXT", info="""The edge of menu system, it shouldn't appear.
    If you are watching it, there is a bug need to be fixed."""},
    {anchor=49, type="TEXT", info="[R2R]", func='clear'}
]